$(document).ready(function() {

  $("button#popUpButton").click(function() {
  alert("LEAVING THIS PAGE NOW MEANS FORFITING FANTASTIC DEALS ON AMAZING THINGS, ARE YOU SURE YOU WANT TO DO THAT? DONT BE SO SURE BECAUSE YOU HAVE TO STAY TO FILL OUT THE SURVEY AND GET ALL YOUR DEALS!!!");
  });
});
